export enum ConfigurationType {
	INPUT = 'INPUT',
	TAGS = 'TAGS',
	NUMBER = 'NUMBER',
	BOOLEAN = 'BOOLEAN',
	TEXT_AREA = 'TEXT_AREA',
	SELECT = 'SELECT',
	LABEL = 'LABEL',
	KNOWLEDGE_BASE = 'KNOWLEDGE_BASE',
	FOLDER_PATH_CHOOSER = 'FOLDER_PATH_CHOOSER',
}
